/**
 */
package eventbase.provider;

import eventbase.util.EventbaseAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EventbaseItemProviderAdapterFactory extends EventbaseAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EventbaseItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.ESequenceFlow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ESequenceFlowItemProvider eSequenceFlowItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.ESequenceFlow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createESequenceFlowAdapter() {
		if (eSequenceFlowItemProvider == null) {
			eSequenceFlowItemProvider = new ESequenceFlowItemProvider(this);
		}

		return eSequenceFlowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.EPeriodicEG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EPeriodicEGItemProvider ePeriodicEGItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.EPeriodicEG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEPeriodicEGAdapter() {
		if (ePeriodicEGItemProvider == null) {
			ePeriodicEGItemProvider = new EPeriodicEGItemProvider(this);
		}

		return ePeriodicEGItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.EPatternedEG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EPatternedEGItemProvider ePatternedEGItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.EPatternedEG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEPatternedEGAdapter() {
		if (ePatternedEGItemProvider == null) {
			ePatternedEGItemProvider = new EPatternedEGItemProvider(this);
		}

		return ePatternedEGItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.EDistributionEG} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EDistributionEGItemProvider eDistributionEGItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.EDistributionEG}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEDistributionEGAdapter() {
		if (eDistributionEGItemProvider == null) {
			eDistributionEGItemProvider = new EDistributionEGItemProvider(this);
		}

		return eDistributionEGItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.ESimpleFilterConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ESimpleFilterConstraintItemProvider eSimpleFilterConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.ESimpleFilterConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createESimpleFilterConstraintAdapter() {
		if (eSimpleFilterConstraintItemProvider == null) {
			eSimpleFilterConstraintItemProvider = new ESimpleFilterConstraintItemProvider(this);
		}

		return eSimpleFilterConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link eventbase.ESimpleEF} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ESimpleEFItemProvider eSimpleEFItemProvider;

	/**
	 * This creates an adapter for a {@link eventbase.ESimpleEF}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createESimpleEFAdapter() {
		if (eSimpleEFItemProvider == null) {
			eSimpleEFItemProvider = new ESimpleEFItemProvider(this);
		}

		return eSimpleEFItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (eSequenceFlowItemProvider != null) eSequenceFlowItemProvider.dispose();
		if (ePeriodicEGItemProvider != null) ePeriodicEGItemProvider.dispose();
		if (ePatternedEGItemProvider != null) ePatternedEGItemProvider.dispose();
		if (eDistributionEGItemProvider != null) eDistributionEGItemProvider.dispose();
		if (eSimpleFilterConstraintItemProvider != null) eSimpleFilterConstraintItemProvider.dispose();
		if (eSimpleEFItemProvider != null) eSimpleEFItemProvider.dispose();
	}

}
