/* Generated By:JavaCC: Do not edit this line. ukuFlowScriptConstants.java */
package de.tu.darmstadt.dvs.ukuflow.script;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ukuFlowScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int XOR = 7;
  /** RegularExpression Id. */
  int NOT = 8;
  /** RegularExpression Id. */
  int BOOLEAN = 9;
  /** RegularExpression Id. */
  int TRUE = 10;
  /** RegularExpression Id. */
  int FALSE = 11;
  /** RegularExpression Id. */
  int LOCAL = 12;
  /** RegularExpression Id. */
  int SCOPE = 13;
  /** RegularExpression Id. */
  int VARIABLE = 14;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 15;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 16;
  /** RegularExpression Id. */
  int HEX_LITERAL = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int EQUAL = 21;
  /** RegularExpression Id. */
  int UNEQUAL = 22;
  /** RegularExpression Id. */
  int GREATERTHAN = 23;
  /** RegularExpression Id. */
  int LESSTHAN = 24;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 25;
  /** RegularExpression Id. */
  int LESSOREQUAL = 26;
  /** RegularExpression Id. */
  int STRING = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "<AND>",
    "<OR>",
    "<XOR>",
    "<NOT>",
    "<BOOLEAN>",
    "<TRUE>",
    "<FALSE>",
    "\"local\"",
    "<SCOPE>",
    "<VARIABLE>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<STRING>",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
