#!/bin/sh

cd ~/workspace/git/ukuflow
rm tests/size-data

# -------------
cd ~/workspace/git/ukuflow/data-mgr

make clean TARGET=sky
make TARGET=sky
msp430-gcc -DDEBUG_DEPTH=0 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/platform/sky/ -DAUTOSTART_ENABLE -c tester/tester.c -o tester/tester.co
msp430-gcc -DDEBUG_DEPTH=0 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/platform/sky/ -MMD -c /Users/guerrero/workspace/contiki/platform/sky/./contiki-sky-main.c -o obj_sky/contiki-sky-main.o
msp430-gcc -DDEBUG_DEPTH=0 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/platform/sky/ -c base64.c -o base64.o
msp430-gcc -DDEBUG_DEPTH=0 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/platform/sky/ -c data-mgr.c -o data-mgr.o
msp430-gcc -DDEBUG_DEPTH=0 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Userskailup430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/platform/sky/ -c expression-eval.c -o expression-eval.o
msp430-gcc -mmcu=msp430f1611 -Wl,-Map=contiki-sky.map -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__  tester/tester.co obj_sky/contiki-sky-main.o base64.o data-mgr.o expression-eval.o contiki-sky.a  -o tester/tester.sky

mv *o obj_sky/
mv tester/tester.co obj_sky/tester.o

make sizeplot TARGET=sky

cat size-data | grep data-mgr >> ../tests/size-data
cat size-data | grep expr >> ../tests/size-data
echo "" >> ../tests/size-data
echo "" >> ../tests/size-data





# -------------
cd ~/workspace/git/ukuflow/scopes
make clean TARGET=sky
make TARGET=sky

msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -DAUTOSTART_ENABLE -c tester/tester.c -o tester/tester.co
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -MMD -c /Users/guerrero/workspace/contiki/platform/sky/./contiki-sky-main.c -o obj_sky/contiki-sky-main.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -c bitvector.c -o bitvector.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -c frag-unicast.c -o frag-unicast.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -c scopes.c -o scopes.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -c scopes-selfur.c -o scopes-selfur.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -c scopes-membership-simple.c -o scopes-membership-simple.o
msp430-gcc -mmcu=msp430f1611 -Wl,-Map=contiki-sky.map -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__  tester/tester.co obj_sky/contiki-sky-main.o bitvector.o frag-unicast.o scopes.o scopes-selfur.o scopes-membership-simple.o contiki-sky.a  -o tester/tester.sky
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/platform/sky/ -DAUTOSTART_ENABLE -c tester/tester_parallel.c -o tester/tester_parallel.co
msp430-gcc -mmcu=msp430f1611 -Wl,-Map=contiki-sky.map -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__  tester/tester_parallel.co obj_sky/contiki-sky-main.o bitvector.o frag-unicast.o scopes.o scopes-selfur.o scopes-membership-simple.o contiki-sky.a  -o tester/tester_parallel.sky

mv *o obj_sky/
mv tester/tester.co obj_sky/tester.o
mv tester/tester_parallel.co obj_sky/tester_parallel.o


make sizeplot TARGET=sky


cat size-data | grep scopes >> ../tests/size-data
cat size-data | grep frag-unicast >> ../tests/size-data
cat size-data | grep bitvector >> ../tests/size-data
echo "" >> ../tests/size-data
echo "" >> ../tests/size-data

# -------------
cd ~/workspace/git/ukuflow/ukuFlow-engine
make clean TARGET=sky
make TARGET=sky

msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -DAUTOSTART_ENABLE -c ukuflow-serial.c -o ukuflow-serial.co
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -MMD -c /Users/guerrero/workspace/contiki/platform/sky/./contiki-sky-main.c -o obj_sky/contiki-sky-main.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c workflow.c -o workflow.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c event.c -o event.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c ukuflow-mgr.c -o ukuflow-mgr.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c ukuflow-engine.c -o ukuflow-engine.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c ukuflow-net-mgr.c -o ukuflow-net-mgr.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c ukuflow-cmd-runner.c -o ukuflow-cmd-runner.o
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -c ukuflow-event-mgr.c -o ukuflow-event-mgr.o
msp430-gcc -mmcu=msp430f1611 -Wl,-Map=contiki-sky.map -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__  ukuflow-serial.co obj_sky/contiki-sky-main.o workflow.o event.o ukuflow-mgr.o ukuflow-engine.o ukuflow-net-mgr.o ukuflow-cmd-runner.o ukuflow-event-mgr.o contiki-sky.a  -o ukuflow-serial.sky
msp430-gcc -DPROJECT_CONF_H=\"project-conf.h\" -DDEBUG_DEPTH=0 -DPROCESS_CONF_NO_PROCESS_NAMES=1 -DCONTIKI=1 -DCONTIKI_TARGET_SKY=1 -Os -fno-strict-aliasing -ffunction-sections -Wall -mmcu=msp430f1611   -I. -I/Users/guerrero/workspace/contiki/platform/sky/. -I/Users/guerrero/workspace/contiki/platform/sky/dev -I/Users/guerrero/workspace/contiki/platform/sky/apps -I/Users/guerrero/workspace/contiki/platform/sky/net -I/Users/guerrero/workspace/contiki/cpu/msp430/f1xxx -I/Users/guerrero/workspace/contiki/cpu/msp430/. -I/Users/guerrero/workspace/contiki/cpu/msp430/dev -I/Users/guerrero/workspace/contiki/core/dev -I/Users/guerrero/workspace/contiki/core/lib -I/Users/guerrero/workspace/contiki/core/net -I/Users/guerrero/workspace/contiki/core/net/mac -I/Users/guerrero/workspace/contiki/core/net/rime -I/Users/guerrero/workspace/contiki/core/net/rpl -I/Users/guerrero/workspace/contiki/core/sys -I/Users/guerrero/workspace/contiki/core/cfs -I/Users/guerrero/workspace/contiki/core/ctk -I/Users/guerrero/workspace/contiki/core/lib/ctk -I/Users/guerrero/workspace/contiki/core/loader -I/Users/guerrero/workspace/contiki/core/. -I/Users/guerrero/workspace/contiki/apps/serial-shell -I/Users/guerrero/workspace/contiki/apps/data-mgr -I/Users/guerrero/workspace/contiki/apps/scopes -I/Users/guerrero/workspace/contiki/apps/shell -I/Users/guerrero/workspace/contiki/apps/webserver -I/Users/guerrero/workspace/contiki/apps/webbrowser -I/Users/guerrero/workspace/contiki/apps/irc -I/Users/guerrero/workspace/contiki/apps/telnet -I/Users/guerrero/workspace/contiki/apps/twitter -I/Users/guerrero/workspace/contiki/apps/powertrace -I/Users/guerrero/workspace/contiki/apps/collect-view -I/Users/guerrero/workspace/contiki/apps/data-mgr -Ishell -I/Users/guerrero/workspace/contiki/platform/sky/ -DAUTOSTART_ENABLE -c tester/tester.c -o tester/tester.co
msp430-gcc -mmcu=msp430f1611 -Wl,-Map=contiki-sky.map -Wl,--gc-sections,--undefined=_reset_vector__,--undefined=InterruptVectors,--undefined=_copy_data_init__,--undefined=_clear_bss_init__,--undefined=_end_of_init__  tester/tester.co obj_sky/contiki-sky-main.o workflow.o event.o ukuflow-mgr.o ukuflow-engine.o ukuflow-net-mgr.o ukuflow-cmd-runner.o ukuflow-event-mgr.o contiki-sky.a  -o tester/tester.sky

mv ukuflow-serial.co obj_sky/ukuflow-serial.o
mv *o obj_sky/
mv tester/tester.co obj_sky/tester.o


make sizeplot TARGET=sky


cat size-data | grep ukuflow  >> ../tests/size-data
cat size-data | grep "event " >> ../tests/size-data
cat size-data | grep workflow  >> ../tests/size-data

nl -bt -nln ../tests/size-data > ../tests/size-data-2
tr ' ' '\t' < ../tests/size-data-2 | tr -s '\t' > ../tests/size-data-3

echo ROM Requirements:
cat ../tests/size-data | cut -f 2 -d \ | awk '{s+=$1} END {print s}'

echo RAM Requirements:
cat ../tests/size-data | cut -f 3 -d \ | awk '{s+=$1} END {print s}'
cd