<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UkuModel" nsURI="http://www.dvs.tu-darmstadt.de/ukuflow" nsPrefix="uku">
  <eClassifiers xsi:type="ecore:EClass" name="DocumentRoot" eSuperTypes="platform:/plugin/org.eclipse.bpmn2/model/BPMN20.ecore#//Documentation"/>
</ecore:EPackage>
