/* Generated By:JavaCC: Do not edit this line. EventBaseScriptConstants.java */
package de.tudarmstadt.dvs.ukuflow.script.eventbasescript;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EventBaseScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int SUB = 9;
  /** RegularExpression Id. */
  int MULTIPLICATIVE = 10;
  /** RegularExpression Id. */
  int COMPOSITION_POLICY = 11;
  /** RegularExpression Id. */
  int EVICTION = 12;
  /** RegularExpression Id. */
  int EVENT_OUTPUT_TYPE = 13;
  /** RegularExpression Id. */
  int EQUALITY = 14;
  /** RegularExpression Id. */
  int RELATIONAL = 15;
  /** RegularExpression Id. */
  int BOOLEAN = 16;
  /** RegularExpression Id. */
  int TRUE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int immediate_EG = 19;
  /** RegularExpression Id. */
  int absolute_EG = 20;
  /** RegularExpression Id. */
  int offset_EG = 21;
  /** RegularExpression Id. */
  int relative_EG = 22;
  /** RegularExpression Id. */
  int functional_EG = 23;
  /** RegularExpression Id. */
  int PEG = 24;
  /** RegularExpression Id. */
  int APEG = 25;
  /** RegularExpression Id. */
  int ADEG = 26;
  /** RegularExpression Id. */
  int SEF = 27;
  /** RegularExpression Id. */
  int AND_COMPOSITION_EF = 28;
  /** RegularExpression Id. */
  int OR_COMPOSITION_EF = 29;
  /** RegularExpression Id. */
  int NOT_COMPOSITION_EF = 30;
  /** RegularExpression Id. */
  int SEQUENCE_COMPOSITION_EF = 31;
  /** RegularExpression Id. */
  int MIN_COMPOSITION_EF = 32;
  /** RegularExpression Id. */
  int MAX_COMPOSITION_EF = 33;
  /** RegularExpression Id. */
  int COUNT_COMPOSITION_EF = 34;
  /** RegularExpression Id. */
  int SUM_COMPOSITION_EF = 35;
  /** RegularExpression Id. */
  int AVG_COMPOSITION_EF = 36;
  /** RegularExpression Id. */
  int STDEV_COMPOSITION_EF = 37;
  /** RegularExpression Id. */
  int INCREASE_EC = 38;
  /** RegularExpression Id. */
  int DECREASE_EC = 39;
  /** RegularExpression Id. */
  int REMAIN_EC = 40;
  /** RegularExpression Id. */
  int TOP = 41;
  /** RegularExpression Id. */
  int SENSOR_TYPE = 42;
  /** RegularExpression Id. */
  int M = 43;
  /** RegularExpression Id. */
  int V = 44;
  /** RegularExpression Id. */
  int A = 45;
  /** RegularExpression Id. */
  int K = 46;
  /** RegularExpression Id. */
  int I = 47;
  /** RegularExpression Id. */
  int POSITIVE_NUMBER = 48;
  /** RegularExpression Id. */
  int BINARY = 49;
  /** RegularExpression Id. */
  int PATTERN = 50;
  /** RegularExpression Id. */
  int REPETITION = 51;
  /** RegularExpression Id. */
  int GAUSSIAN_DISTRIBUTION = 52;
  /** RegularExpression Id. */
  int CHI_SQUARE_DISTRIBUTION = 53;
  /** RegularExpression Id. */
  int PARETO_DISTRIBUTION = 54;
  /** RegularExpression Id. */
  int IDENTIFIER = 55;
  /** RegularExpression Id. */
  int LETTER = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "\"+\"",
    "\"-\"",
    "<MULTIPLICATIVE>",
    "<COMPOSITION_POLICY>",
    "<EVICTION>",
    "<EVENT_OUTPUT_TYPE>",
    "<EQUALITY>",
    "<RELATIONAL>",
    "<BOOLEAN>",
    "<TRUE>",
    "<FALSE>",
    "\"IMMEDIATE_EG\"",
    "\"ABSOLUTE_EG\"",
    "\"OFFSET_EG\"",
    "\"RELATIVE_EG\"",
    "\"FUNCTIONAL_EG\"",
    "\"PERIODIC_EG\"",
    "\"PATTERN_EG\"",
    "\"DISTRIBUTION_EG\"",
    "\"SIMPLE_EF\"",
    "\"AND_EC\"",
    "\"OR_EC\"",
    "\"NOT_EC\"",
    "\"SEQUENCE_EC\"",
    "\"MIN_EC\"",
    "\"MAX_EC\"",
    "\"COUNT_EC\"",
    "\"SUM_EC\"",
    "\"AVG_EC\"",
    "\"STDEV_EC\"",
    "\"INCREASE_EC\"",
    "\"DECREASE_EC\"",
    "\"REMAIN_EC\"",
    "\"TOP\"",
    "<SENSOR_TYPE>",
    "<M>",
    "<V>",
    "<A>",
    "<K>",
    "<I>",
    "<POSITIVE_NUMBER>",
    "<BINARY>",
    "<PATTERN>",
    "<REPETITION>",
    "\"GAUSSIAN_DISTRIBUTION\"",
    "\"CHI_SQUARE_DISTRIBUTION\"",
    "\"PARETO_DISTRIBUTION\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
    "\"@s\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\":\"",
    "\"#\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
  };

}
