/* Generated By:JavaCC: Do not edit this line. EventBaseScriptConstants.java */
package de.tudarmstadt.dvs.ukuflow.script.eventbasescript;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EventBaseScriptConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int COMPOSITION_POLICY = 8;
  /** RegularExpression Id. */
  int EVICTION = 9;
  /** RegularExpression Id. */
  int EVENT_OUTPUT_TYPE = 10;
  /** RegularExpression Id. */
  int COMPARISON = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int TRUE = 13;
  /** RegularExpression Id. */
  int FALSE = 14;
  /** RegularExpression Id. */
  int immediate_EG = 15;
  /** RegularExpression Id. */
  int absolute_EG = 16;
  /** RegularExpression Id. */
  int offset_EG = 17;
  /** RegularExpression Id. */
  int relative_EG = 18;
  /** RegularExpression Id. */
  int functional_EG = 19;
  /** RegularExpression Id. */
  int PEG = 20;
  /** RegularExpression Id. */
  int APEG = 21;
  /** RegularExpression Id. */
  int ADEG = 22;
  /** RegularExpression Id. */
  int SEF = 23;
  /** RegularExpression Id. */
  int CEF = 24;
  /** RegularExpression Id. */
  int TOP = 25;
  /** RegularExpression Id. */
  int SENSOR_TYPE = 26;
  /** RegularExpression Id. */
  int POSITIVE_NUMBER = 27;
  /** RegularExpression Id. */
  int BINARY = 28;
  /** RegularExpression Id. */
  int PATTERN = 29;
  /** RegularExpression Id. */
  int REPETITION = 30;
  /** RegularExpression Id. */
  int IDENTIFIER = 31;
  /** RegularExpression Id. */
  int LETTER = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<COMPOSITION_POLICY>",
    "<EVICTION>",
    "<EVENT_OUTPUT_TYPE>",
    "<COMPARISON>",
    "<BOOLEAN>",
    "<TRUE>",
    "<FALSE>",
    "\"IMMEDIATE_EG\"",
    "\"ABSOLUTE_EG\"",
    "\"OFFSET_EG\"",
    "\"RELATIVE_EG\"",
    "\"FUNCTIONAL_EG\"",
    "\"PERIODIC_EG\"",
    "\"PATTERN_EG\"",
    "\"DISTRIBUTION_EG\"",
    "\"SIMPLE_EF\"",
    "\"COMPLEX_EF\"",
    "\"TOP\"",
    "<SENSOR_TYPE>",
    "<POSITIVE_NUMBER>",
    "<BINARY>",
    "<PATTERN>",
    "<REPETITION>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"=\"",
    "\"@s\"",
    "\"(\"",
    "\")\"",
    "\"^\"",
    "\":\"",
    "\"-\"",
    "\"i\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
    "\"/\"",
  };

}
