#Version with scopes-flooding:
#scopes_src = bitvector.c frag_unicast.c scopes.c scopes-flooding.c scopes-membership-simple.c 
#Version with scopes-selfur:
scopes_src = bitvector.c frag-unicast.c scopes.c scopes-selfur.c scopes-membership-simple.c

APPS += data-mgr